version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - db_data:/app/db.sqlite3
    env_file:
      - .env
    command: python app.py
    restart: always

volumes:
  db_data:
