services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - db_data:/app/data
    env_file:
      - .env.production
    restart: always
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data:
