version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - FLASK_ENV=development
    command: python app.py
